# Generated by Django 4.0.6 on 2022-12-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='post',
        ),
        migrations.AddField(
            model_name='likes',
            name='postId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
